### ISSUE TITLE
Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by afasciaux** [BitBagCommerce/SyliusElasticsearchPlugin#97] opened 2019-10-28 13:32 UTC
Hi, 
Got an error when trying ti populate.
Is there any problem between Elasticsearch version server and bundle ?

Thanks !!

Root mapping definition has unsupported parameters:  [default : {dynamic_date_formats=[], _meta={model=App\Entity\Product\MainProduct}, properties={enabled={type=text}}}] [reason: Failed to parse mapping [_doc]: Root mapping definition has unsupported  
   parameters:  [default : {dynamic_date_formats=[], _meta={model=App\Entity\Product\MainProduct}, properties={enabled={type=text}}}]]

**Comment by alexweggs** [comment] 2019-10-28 14:54
Ok seems to be solved with ES 6 version !

Everything is ok now but can't dispaly facets on front, not too far i guess ;)

**Comment by Bodarev** [comment] 2020-03-28 10:35
Hello,
which ES 6 version did you used?
I tried ES 6.8 version, and have the following error - http://joxi.ru/823VLYEiDbPlPm

Can you tell me which version did you used? or how did you solve the problem specifically?

**Comment by hipachka** [comment] 2020-04-24 08:17
try to use 6.8.3

**Comment by bartektw** [comment] 2020-11-03 08:19
Hi @afasciaux! The problem is related to your ES version. In documentation you can find information about supported versions.

"_Note: This Plugin currently supports ElasticSearch 5.3.x up to 6.8.x. ElasticSearch ^7.x is not currently supported._"

**Comment by afasciaux** [comment] 2020-11-26 22:01
Hi @bartektw , i tried with the v2.0.0-beta1 (ES7 integration) but still same error.

Any chance that someone tried to run this tag with ES7 ?

**Comment by leszczuu** [comment] 2024-08-22 08:25
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html

Current version(v4.0.2) supports ElasticSearch 7.0 and above.
I tested with elasticsearch:7.17.23 and it seems to work fine. 
Closing this as no longer relevant / reproducible.

**Closed by leszczuu** 2024-08-22 08:25 UTC
