### ISSUE TITLE
Why Filters management is different between search and listing (taxon) ?  

### ISSUE THREAD

**Issue by flochntrl** [BitBagCommerce/SyliusElasticsearchPlugin#211] opened 2022-10-20 12:54 UTC
I don't understand why facets are not implemented on taxon listing

**Comment by leszczuu** [comment] 2024-08-22 10:43
Tested latest version v4.0.2 

![image](https://github.com/user-attachments/assets/76e1ef90-aab2-4751-a9d8-8996f81f8685)
![image](https://github.com/user-attachments/assets/716436eb-c44d-444e-bd85-f60477d3d7ac)

both forms use same listener for facets:
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/Form/Type/SearchType.php#L38
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/Form/Type/ShopProductsFilterType.php#L36
 
 so facet filters should be identical.
 
 Missing price filter is not a bug, and can be added with customization.
 
 closing as no longer relevant.

**Closed by leszczuu** 2024-08-22 10:43 UTC
